FROM debian:10

RUN apt update
RUN apt -y install apt-transport-https gnupg wget
RUN wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add -

COPY php.list /etc/apt/sources.list.d

RUN mkdir /usr/local/ioncube
COPY ioncube_loader_lin_7.2.so /usr/local/ioncube
COPY ioncube_loader_lin_7.2_ts.so /usr/local/ioncube

RUN apt update

RUN apt -y install apache2 \
php7.2 \
php7.2-cli \
php7.2-common \
php7.2-curl \
php7.2-gd \
php7.2-json \
php7.2-mysql \
php7.2-readline \
apache2 \
&& apt-get clean

COPY 00-iocube.ini /etc/php/7.2/apache2/conf.d
RUN sed -i 's/\/var\/www\/html/\/var\/www\/html\/sismadak/g' /etc/apache2/sites-enabled/000-default.conf
EXPOSE 80

CMD ["apache2ctl", "-D",  "FOREGROUND"]
